---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- INNER JOIN on [chc].[vw_000_Header_Current] returns latest record per reporting period (re-submissions create duplicates which are all within the Header table, so view excludes the earlier versions) 
-- View also creates calculation of RecordEndDate based on the following record's RecordStartDate (RecordEndDate = NULL indicates the latest record)
-- Descriptive columns brought in from relevant reference tables [NHSE_Sandbox_CHC].[dbo].[PLDS.Ref_] 
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

SELECT a.[CHC_Load_ID]
      ,[ServiceRequestId]
      ,[LocalPatientId]
      ,[ActivityTypeCHC]
      ,CASE WHEN [a].[ActivityTypeCHC] IS NULL THEN 'BLANK' ELSE COALESCE((SELECT [ActivityTypeCHC] FROM [NHSE_Sandbox_CHC].[dbo].[PLDS.Ref_Activity_Type] WHERE [Code]=[a].[ActivityTypeCHC]),'INVALID') END [ActivityTypeCHC_Ref]
      ,[ReferralRequestReceivedDateCHC]
      ,[RefRequestStandardCHC]
      ,CASE WHEN [a].[RefRequestStandardCHC] IS NULL THEN 'BLANK' ELSE COALESCE((SELECT [RefRequestType] FROM [NHSE_Sandbox_CHC].[dbo].[PLDS.Ref_Request_Type] WHERE [Code]=[a].[RefRequestStandardCHC]),'INVALID') END [RefRequestStandardCHC_Ref]
      ,[SourceOfReferralCHC]
      ,CASE WHEN [a].[SourceOfReferralCHC] IS NULL THEN 'BLANK' ELSE COALESCE((SELECT [SourceofRef] FROM [NHSE_Sandbox_CHC].[dbo].[PLDS.Ref_Source_of_Ref] WHERE [Code]=[a].[SourceOfReferralCHC]),'INVALID') END [SourceOfReferralCHC_Ref]
      ,[ReferringCareProfessionalStaffTypeStandardCHC]
      ,CASE WHEN [a].[ReferringCareProfessionalStaffTypeStandardCHC] IS NULL THEN 'BLANK' ELSE COALESCE((SELECT [RefCareProfType] FROM [NHSE_Sandbox_CHC].[dbo].[PLDS.Ref_CareProfType] WHERE [Code]=[a].[ReferringCareProfessionalStaffTypeStandardCHC]),'INVALID') END [ReferringCareProfessionalStaffTypeStandardCHC_Ref]
      ,[CHCStandardChecklistCompletionDate]
      ,[CHCFastTrackToolCompletionDate]
      ,[PatientLocationCHCChecklist]
      ,CASE WHEN [a].[PatientLocationCHCChecklist] IS NULL THEN 'BLANK' ELSE COALESCE((SELECT [Ref_Patient_Location] FROM [NHSE_Sandbox_CHC].[dbo].[PLDS.Ref_Patient_Location] WHERE [Code]=[a].[PatientLocationCHCChecklist]),'INVALID') END [PatientLocationCHCChecklist_Ref]
      ,[ApprClinicalStaffGroupFastTrack]
      ,CASE WHEN [a].[ApprClinicalStaffGroupFastTrack] IS NULL THEN 'BLANK' ELSE COALESCE((SELECT [Ref_Patient_Location] FROM [NHSE_Sandbox_CHC].[dbo].[PLDS.Ref_Clinical_Staff_Group] WHERE [Code]=[a].[ApprClinicalStaffGroupFastTrack]),'INVALID') END [ApprClinicalStaffGroupFastTrack_Ref]
      ,[RefNotificationOutcomeStandardCHC]
      ,CASE WHEN [a].[RefNotificationOutcomeStandardCHC] IS NULL THEN 'BLANK' ELSE COALESCE((SELECT [Ref_Ref_Notification_Outcome] FROM [NHSE_Sandbox_CHC].[dbo].[PLDS.Ref_Ref_Notification_Outcome] WHERE [Code]=[a].[RefNotificationOutcomeStandardCHC]),'INVALID') END [RefNotificationOutcomeStandardCHC_Ref]
      ,[RefDiscountReasonCHC]
      ,CASE WHEN [a].[RefDiscountReasonCHC] IS NULL THEN 'BLANK' ELSE COALESCE((SELECT [Ref_RefDiscountReason] FROM [NHSE_Sandbox_CHC].[dbo].[PLDS.Ref_RefDiscountReason] WHERE [Code]=[a].[RefDiscountReasonCHC]),'INVALID') END [RefDiscountReasonCHC_Ref]
      ,[RefDiscountedDateStandardCHC]
      ,[RefAcceptedDateFastTrack]
      ,[PatientSettingDecisionSupportToolStandardCHC]
      ,CASE WHEN [a].[PatientSettingDecisionSupportToolStandardCHC] IS NULL THEN 'BLANK' ELSE COALESCE((SELECT [Ref_PatientSettingDecSupT] FROM [NHSE_Sandbox_CHC].[dbo].[PLDS.Ref_PatientSettingDecSupT] WHERE [Code]=[a].[PatientSettingDecisionSupportToolStandardCHC]),'INVALID') END [PatientSettingDecisionSupportToolStandardCHC_Ref]
      ,[DecSupportToolCompletionDateStandardCHC]
      ,[MDTRecommendationStandardCHC]
      ,CASE WHEN [a].[MDTRecommendationStandardCHC] IS NULL THEN 'BLANK' ELSE COALESCE((SELECT [Ref_MDTRecommendation] FROM [NHSE_Sandbox_CHC].[dbo].[PLDS.Ref_MDTRecommendation] WHERE [Code]=[a].[MDTRecommendationStandardCHC]),'INVALID') END [MDTRecommendationStandardCHC_Ref]
      ,[CommEligibilityDecisionDateStandardCHC]
      ,[CommEligibilityDecisionOutcomeStandardCHC]
      ,CASE WHEN [a].[CommEligibilityDecisionOutcomeStandardCHC] IS NULL THEN 'BLANK' ELSE COALESCE((SELECT [Ref_CommEligiDecisionOutcome] FROM [NHSE_Sandbox_CHC].[dbo].[PLDS.Ref_CommEligiDecisionOutcome] WHERE [Code]=[a].[CommEligibilityDecisionOutcomeStandardCHC]),'INVALID') END [CommEligibilityDecisionOutcomeStandardCHC_Ref]
      ,[CommEligibilityDecisionSentToPatientDateStandardCHC]
      ,[StartDatePUPOCReqPeriod]
      ,[EndDatePUPOCReqPeriod]
      ,[StartDatePUPOCAgreedPeriod]
      ,[EndDatePUPOCAgreedPeriod]
      ,[ReqReceivedByCommDate]
      ,[LocalResolutionMeetingDateInformal]
      ,[LocalResolutionMeetingDateFormal]
      ,[CommReviewOutcome]
      ,CASE WHEN [a].[CommReviewOutcome] IS NULL THEN 'BLANK' ELSE COALESCE((SELECT [Ref_CommReviewOutcome] FROM [NHSE_Sandbox_CHC].[dbo].[PLDS.Ref_CommReviewOutcome] WHERE [Code]=[a].[CommReviewOutcome]),'INVALID') END [CommReviewOutcome_Ref]
      ,[StartDateLocalResolution]
      ,[EndDateLocalResolution]
      ,[LocalResolutionDecisionSentToPatientDate]
      ,[StartDateFunding]
      ,[EndDateFunding]
      ,[DateEligibilityBeginsLocalResolution]
      ,[PupocDecisionMadeDate]
      ,[PupocDecisionOutcome]
      ,CASE WHEN [a].[PupocDecisionOutcome] IS NULL THEN 'BLANK' ELSE COALESCE((SELECT [Ref_PupocDecisionOutcome] FROM [NHSE_Sandbox_CHC].[dbo].[PLDS.Ref_PupocDecisionOutcome] WHERE [Code]=[a].[PupocDecisionOutcome]),'INVALID') END [PupocDecisionOutcome_Ref]
      ,[EligiablityDecisionSentDatePUPOC]
      ,a.[Effective_From]
      ,[RecordNumber]
      ,[CHC101UniqID]
      ,a.[OrgIDComm]
      ,a.[UniqSubmissionID]
      ,[UniqServReqID]
      ,[AgeServReferRecDateYears]
      ,[Reg_GP_Activity]
      ,[PCD_Indicator]
      ,[RecordStartDate]
      ,DATEADD(d,-1,LAG(RecordStartDate,1) OVER(PARTITION BY ServiceRequestID, LocalPatientID ORDER BY RecordStartDate DESC)) [RecordEndDate]
      ,a.[Sub_OrgIDComm] [Sub_OrgID_Comm]
      ,a.[Der_LoadDate]
      ,a.[Der_FileName]
      ,a.Token_person_ID

 FROM  [NHSE_Sandbox_CHC].[chc].[101_ReferralAssessmentOutcome] a 
  INNER JOIN [NHSE_Sandbox_CHC].[chc].[vw_reporting_000_Header_Current] b --
  ON a.CHC_Load_ID=b.CHC_Load_ID
  AND a.UniqSubmissionID=b.UniqSubmissionID
